In [21]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import seaborn as sns
import sys
import math
%matplotlib inline

In [20]:
def load_data(stat_metrics_file):
    """Loads the data from the given stat_metric and sys_metric files."""
    stat_metrics = pd.read_csv(stat_metrics_file)
    stat_metrics.sort_values(by='Round', inplace=True)
    return stat_metrics

In [14]:
def get_accuracy_vs_round_number(stat_metrics, refined=True):
    accuracy_key = 'Average Test Acc'
    accuracies = stat_metrics.groupby('Round', as_index=False).mean()
    return accuracies['Round'].as_matrix(), accuracies[accuracy_key].as_matrix()

In [27]:
def max_from_directory(data_dir, refined=True, column = 'val'):
    files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]
    
    accuracies = []
    rounds = []
    print(str(len(files)) + " files")
    
    if len(files) > 0:
        print("Reached Here")
        print(data_dir)
        for f in files:
            print(f)
            metrics = load_data(os.path.join(data_dir, f))
            round_numbers, acc = get_accuracy_vs_round_number(metrics, refined)

            accuracies.append(acc)
            rounds.append(len(round_numbers))
            print(round_numbers)
            print(str(100 * acc))
            #print(accuracies)
        
        accuracies = 100 * np.array(accuracies)
        if len(files) > 1:
            #accuracies = np.mean(accuracies, axis=0)
            #return accuracies[-1]
            
            last_acc = 0
            for i in range(len(files)):
                last_acc += accuracies[i][-1]
            last_acc /= len(files)    
            
            print(str(last_acc))
            print("")
    
            return last_acc
        print(accuracies[0,-1])
        print("")
        return accuracies[0,-1]
        

In [33]:
def print_accs_from_files(data_dir, refined=True):
    files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]
    
    for f in files:
        metrics = load_data(os.path.join(data_dir, f))
        round_numbers, acc = get_accuracy_vs_round_number(metrics, refined)
        
        print(data_dir, f)
        print(100 * np.array(acc))

In [36]:
DIR = 'results/convex_case/hyper_search/10_shot_5_way/noiseless/'
all_dirs = [x[0] for x in os.walk(DIR) if not x[0] == DIR]
all_accs = [(max_from_directory(path, column='Average Test Acc', refined=False), path) for path in all_dirs]
all_accs = [(acc, path) for acc, path in all_accs if not math.isnan(acc)]
best = max([acc for acc, _ in all_accs])
all_accs_user_level = all_accs
all_accs_user_level



1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0050_dp_sgd_lr_0.0010_train_shots10.00
seed_8164600.csv
[    0.   200.   400.   600.   800.  1000.]
[ 33.72  32.32  34.52  33.86  33.28  34.32]
34.32

1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0071_dp_sgd_lr_0.0010_train_shots10.00
seed_8164600.csv
[    0.   200.   400.   600.   800.  1000.]
[ 48.38  49.48  49.48  50.14  50.02  49.52]
49.52

1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0100_dp_sgd_lr_0.0010_train_s

[    0.   200.   400.   600.   800.  1000.]
[ 20.    20.46  19.92  19.64  20.38  20.16]
20.16

1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch15.00_grad_10.00000_noise_multiplier_0.5100_meta_step_1.4142_meta_step_final_0.0000_learning_rate_0.0071_dp_sgd_lr_0.0010_train_shots10.00
seed_8164600.csv
[    0.   200.   400.   600.   800.  1000.]
[ 21.38  22.14  20.98  22.    21.46  21.46]
21.46

1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch15.00_grad_10.00000_noise_multiplier_0.5100_meta_step_1.4142_meta_step_final_0.0000_learning_rate_0.1000_dp_sgd_lr_0.0010_train_shots10.00
seed_8164600.csv
[    0.   200.   400.   600.   800.  1000.]
[ 58.32  49.9   49.88  51.66  53.34  55.06]
55.06

1 files
Reached Here
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch15.00_grad_10.00000_noise_multi

[(34.32,
  'results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0050_dp_sgd_lr_0.0010_train_shots10.00'),
 (49.519999999999996,
  'results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0071_dp_sgd_lr_0.0010_train_shots10.00'),
 (21.02,
  'results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.0100_dp_sgd_lr_0.0010_train_shots10.00'),
 (70.820000000000007,
  'results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning

In [37]:
best_path = [path for acc, path in all_accs if acc == best]
print(best, best_path)
for p in best_path:
    print_accs_from_files(p, refined=False)

70.82 ['results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.1000_dp_sgd_lr_0.0010_train_shots10.00']
results/convex_case/hyper_search/10_shot_5_way/noiseless/meta_batches_1.0_meta_iters_1000.0_inner_batch1.00_grad_10.00000_noise_multiplier_0.5100_meta_step_0.0100_meta_step_final_0.0000_learning_rate_0.1000_dp_sgd_lr_0.0010_train_shots10.00 seed_8164600.csv
[ 70.14  69.8   70.78  70.84  70.98  70.82]
